// Bilingual copy for Qerub. Spanish is "neutral" (avoids vosotros/España-isms where possible).

// ── DATOS DE CONTACTO ───────────────────────────────────────────────────────
// Fuente única de los datos de contacto: edítalos aquí y se aplican en toda la web.
window.QERUB_CONTACT = {
  email:   'info@qerub.com',
  phone:   '+34 615 60 07 07',
  hoursEs: 'Lun–Vie · 9:00–18:00 CET · España y Latinoamérica',
  hoursEn: 'Mon–Fri · 9:00–18:00 CET · Spain & Latin America',
};
// ────────────────────────────────────────────────────────────────────────────

window.QERUB_COPY = {
  es: {
    locale: 'es',
    nav: {
      services: 'Servicios',
      method: 'Método',
      sectors: 'Sectores',
      resources: 'Recursos',
      about: 'Sobre Qerub',
      contact: 'Contacto',
      cta: 'Solicitar diagnóstico',
    },
    hero: {
      eyebrow: 'Consultoría IT para empresas en crecimiento',
      title: 'Tu equipo de IT senior,\ncon precio y alcance cerrados.',
      sub: 'IA, datos, software a medida y ciberseguridad. Lo que una gran firma te cobraría en horas, nosotros lo entregamos como resultado. Sin junior facturados.',
      primary: 'Solicitar diagnóstico',
      secondary: 'Ver lo que hacemos',
      tag: 'Q-Start · Diagnóstico cerrado en 7 días hábiles',
      presence: 'Tres husos horarios · España · Argentina · EE.UU.',
      slides: [
        {
          title: 'Tu equipo de IT senior,\ncon precio y alcance cerrados.',
          sub: 'IA, datos, software a medida y ciberseguridad. Lo que una gran firma te cobraría en horas, nosotros lo entregamos como resultado. Sin junior facturados.',
        },
        {
          title: 'Del piloto a producción.\nSin handoffs, sin PowerPoint.',
          sub: 'Llevamos tus agentes de IA, tu plataforma de datos y tu software a medida hasta producción — gobernados y seguros. Un solo socio para IA, datos, software y ciberseguridad.',
        },
        {
          title: 'Talento senior integrado\nen tu equipo en días, no en meses.',
          sub: 'Equipos senior de IA, datos, cloud y ciberseguridad que trabajan en tu huso horario y se integran como tuyos. Pagas resultado, no sillas.',
        },
      ],
    },
    trust: {
      title: 'Trabajamos con los marcos de referencia que importan',
      items: ['NIST CSF 2.0', 'CIS Controls IG1', 'ENISA SME', 'INCIBE', 'CISA', 'NIS2'],
    },
    pillars: {
      eyebrow: 'Lo que hacemos',
      title: 'Un solo socio senior para los cuatro frentes.',
      sub: 'Qerub es una consultora IT para pymes y medianas empresas (50-300 empleados): cubre cuatro frentes con un mismo equipo senior y precio cerrado — IA y datos, software a medida, equipos senior integrados y ciberseguridad. Sin junior facturados, y operando en tres husos horarios: España, Argentina y Estados Unidos.',
      items: [
        {
          code: 'Q-Secure',
          t: 'Ciberseguridad',
          tagline: 'Seguridad como ventaja de negocio, no como freno.',
          intro: 'Q-Secure es el pilar más maduro de Qerub: nueve servicios de ciberseguridad con alcance y precio cerrados, alineados con NIST CSF 2.0, CIS Controls IG1 y NIS2.',
          forWhom: 'CEO · CISO · IT',
          status: 'Operativo',
          to: 'services',
          subs: [
            { n: 'Q-Start · Diagnóstico de ciberseguridad', d: 'Auditamos correo, identidad, Microsoft 365 o Google Workspace, web pública, TLS, copias y plan de respuesta. Scorecard ejecutivo, top 15 riesgos y roadmap de 90 días en 7 días hábiles.', href: '/servicios/auditoria-ciberseguridad-pymes' },
            { n: 'Q-365 Shield · Seguridad Microsoft 365', d: 'Hardening de identidad y tenant: MFA forzado, Conditional Access, revisión de forwarding y accesos privilegiados, etiquetado externo, copias y retención.', href: '/servicios/seguridad-microsoft-365-empresa' },
            { n: 'Q-Mail Shield · Correo seguro y anti-fraude BEC', d: 'SPF, DKIM y DMARC bien desplegados, banners de correo externo, doble aprobación para cambios bancarios y playbook anti-fraude del CEO y proveedores.', href: '/servicios/email-bec-spf-dkim-dmarc' },
            { n: 'Q-Phishing Test · Simulación de phishing y concienciación', d: 'Campañas cortas y continuas en español neutro, con microlearning post-clic y reporting ejecutivo mensual. No un PDF anual.', href: '/servicios/simulacion-phishing-empresa' },
            { n: 'Q-Incident · Plan de respuesta a incidentes', d: 'Playbook a medida con roles, decisiones y contactos, prueba de restauración de copias y un simulacro de mesa con tu equipo directivo.', href: '/servicios/plan-respuesta-incidentes-pyme' },
            { n: 'Q-CISO · vCISO y continuidad', d: 'Gobierno práctico mensual: riesgo vivo, seguimiento de acciones, mini comité, drill de incidentes y carpeta de evidencias para NIS2 o auditorías.', href: '/servicios/vciso-pyme' },
            { n: 'Q-Dark Alert · Vigilancia de dark web y filtraciones', d: 'Monitorizamos dark web, foros y volcados de datos en busca de credenciales, dominios y marca de tu empresa. Si algo aparece, recibes alerta con plan de acción.', href: '/servicios/vigilancia-dark-web-empresa' },
            { n: 'Q-Insure · Preparación para el ciberseguro', d: 'Te dejamos a punto para contratar o renovar un ciberseguro: evaluación previa, respuesta al cuestionario de la aseguradora y cierre de los controles mínimos.', href: '/servicios/ciberseguro-pyme' },
            { n: 'Q-AI Ready · Seguridad del uso de IA', d: 'Política de uso de IA, evaluación de herramientas, configuración segura de Copilot en Microsoft 365 y formación corta. Tu equipo ya usa ChatGPT, Copilot o Gemini.', href: '/servicios/seguridad-ia-empresa' },
          ],
        },
        {
          code: 'Q-Intelligence',
          t: 'IA y Datos',
          tagline: 'Tienes los datos. Te falta convertirlos en decisiones — y en IA que llega a producción.',
          intro: 'Q-Intelligence es el frente de IA y datos de Qerub: lleva la inteligencia artificial del caso de uso a producción con ROI medible, ordena tus datos para BI self-service y gobierna el uso de IA bajo el EU AI Act.',
          forWhom: 'CEO · CIO',
          status: 'Disponible',
          to: 'contact',
          href: '/servicios/consultoria-ia-datos-empresa',
          subs: [
            { n: 'Diagnóstico de IA-readiness', d: 'En 7 días localizamos dónde están tus datos, qué decisión vale la pena automatizar y una estimación realista. Sales con un caso priorizado.' },
            { n: 'IA generativa aplicada', d: 'Agentes, asistentes y RAG sobre tu propia documentación, con recuperación segura y trazabilidad de cada respuesta.' },
            { n: 'Adopción de Copilot M365', d: 'Despliegue de Microsoft Copilot por área con casos de uso reales y formación; el valor está en el uso, no en la licencia. Coordinado con Q-365 Shield.' },
            { n: 'Plataforma de datos y BI', d: 'Datos ordenados y un BI self-service (Power BI) que tu comité abre y entiende. "AI-ready data": calidad y gobierno del dato.' },
            { n: 'Gobierno de IA (EU AI Act)', d: 'Inventario de usos, política y control del riesgo, y descubrimiento de la "shadow AI" de tu equipo. Cumplimiento documentado, no PowerPoint.' },
            { n: 'Puesta en producción', d: 'Despliegue, monitorización, alertas de deriva y transferencia a tu equipo. Sin dependencia eterna.' },
          ],
        },
        {
          code: 'Q-Build',
          t: 'Software a medida',
          tagline: 'El software que tu negocio necesita y el estándar no te da.',
          intro: 'Q-Build es el frente de software a medida de Qerub: aplicaciones, integraciones y modernización con criterio senior y seguridad desde el diseño. El código y los datos son del cliente.',
          forWhom: 'CEO · CTO',
          status: 'Disponible',
          to: 'contact',
          href: '/servicios/desarrollo-software-medida-empresa',
          subs: [
            { n: 'Desarrollo a medida', d: 'Aplicaciones y herramientas internas que encajan con tu operación real, no al revés. Web, paneles y automatizaciones.' },
            { n: 'Integraciones', d: 'Conectamos CRM, ERP, facturación, pagos y APIs para que tus sistemas dejen de hablar idiomas distintos.' },
            { n: 'Modernización de aplicaciones', d: 'Sacamos tu legacy del cuello de botella, por trozos y sin parar el negocio — el paso previo para poder usar IA y datos.' },
            { n: 'MVP con criterio senior', d: 'De idea a producto usable, con decisiones acertadas en lo que importa: identidad, pagos y datos regulados. Anti "vibe coding".' },
            { n: 'Cloud-native', d: 'Desplegado en tu nube (Azure/AWS) con buenas prácticas de coste y operación. Sin sorpresas en la factura.' },
            { n: 'Seguridad desde el diseño', d: 'Nuestra raíz es la ciberseguridad: cada desarrollo nace con identidad, secretos y datos bien tratados.' },
          ],
        },
        {
          code: 'Q-Pod',
          t: 'Equipos senior integrados',
          tagline: 'Talento senior que se integra en tu equipo en días. Pagas resultado, no sillas.',
          intro: 'Q-Pod es el frente de staff augmentation y operación gestionada de Qerub: perfiles senior que se integran en tu equipo en días, en tu huso horario. Pagas resultado, no sillas.',
          forWhom: 'Dir. de Talento · CIO',
          status: 'Disponible',
          to: 'contact',
          href: '/servicios/staff-augmentation-nearshore',
          subs: [
            { n: 'Perfiles senior', d: 'Data engineers, desarrolladores backend, especialistas cloud y de ciberseguridad. Compartimos CV, años y stack antes de incorporar a nadie.' },
            { n: 'Integración en tu equipo', d: 'Trabajan bajo tu backlog y tus herramientas, como uno más — no una caja negra que entrega y desaparece.' },
            { n: 'Nearshore en tres husos', d: 'España, Argentina (UTC-3) y EE.UU., con solape horario real para iterar el mismo día. Inglés alto, cercanía y calidad.' },
            { n: 'vCISO y vCIO/vCTO fraccional', d: 'Operación gestionada: un veterano unas horas a la semana en lugar de un C-level a tiempo completo que no puedes permitirte.' },
            { n: 'SLA de sustitución', d: 'Si en las dos primeras semanas el perfil no encaja, lo cambiamos sin coste. 100% senior, sin junior facturados.' },
            { n: 'Salida limpia', d: 'El conocimiento, el código y los datos son tuyos. Documentamos y transferimos. Sin dependencia eterna.' },
          ],
        },
      ],
      note: 'Q-Secure es nuestro pilar más maduro. Q-Intelligence y Q-Build se entregan con alcance acotado, precio cerrado y total transparencia.',
    },
    decisors: {
      eyebrow: 'Para quién trabajamos',
      title: 'Hablamos el idioma de quien decide.',
      sub: 'Tres conversaciones distintas, un mismo principio: claridad, seniority y precio cerrado.',
      items: [
        { role: 'Para el CEO', t: 'Tecnología que tu comité entiende a la primera.', d: 'IA, datos, software y ciberseguridad con precio y alcance cerrados. Sin sorpresas, sin junior facturados.', cta: 'Una conversación, sin presentación comercial' },
        { role: 'Para el CIO / CTO', t: 'Del piloto a producción, sin PowerPoint.', d: 'Un solo socio para IA, datos, software y seguridad — gobernado, seguro e integrado en tu stack. El código y los datos son tuyos.', cta: 'Reserva una revisión técnica de tu stack' },
        { role: 'Para el Director de Talento', t: 'Talento senior en tu equipo en días, no en meses.', d: 'Equipos senior que trabajan en tu huso horario y se integran como tuyos. Terna en 5–10 días. Sin junior facturados.', cta: 'Cuéntanos qué perfil te falta' },
      ],
    },
    proof: {
      eyebrow: 'Cómo trabajamos',
      title: 'Sin folleto. Prueba de método, no promesas.',
      sub: 'Somos una firma joven y lo decimos claro: nuestra credibilidad está en el método, la transparencia y el talento senior — no en cifras de cliente infladas.',
      metrics: [
        { v: '7', u: 'días', label: 'del diagnóstico al plan de acción' },
        { v: '5–10', u: 'días', label: 'para presentarte una terna senior' },
        { v: '100', u: '%', label: 'perfiles senior · sin junior facturados' },
        { v: '0', u: '€', label: 'sorpresas: precio y alcance cerrados antes de empezar' },
      ],
      cta: {
        tag: 'Empieza por aquí',
        t: 'Arranca con un diagnóstico de bajo riesgo.',
        d: 'Definimos alcance y precio cerrados antes de empezar y validamos el caso con ROI claro antes de escalar. Sin compromisos largos y con total transparencia.',
        cta: 'Hablar con un socio senior',
      },
    },
    geo: {
      eyebrow: 'Dónde estamos',
      title: 'Operamos en tres husos horarios.',
      sub: 'Rigor regulatorio europeo, talento senior en Latinoamérica y cercanía comercial en Estados Unidos. Cerca de tu negocio, a la hora que lo necesitas.',
      items: [
        { city: 'España', role: 'Cumplimiento europeo', d: 'RGPD, NIS2 y EU AI Act. Cara comercial para Europa.' },
        { city: 'Argentina', role: 'Entrega senior nearshore', d: 'Talento senior en huso UTC-3, con solape horario con toda América e inglés alto.' },
        { city: 'Estados Unidos', role: 'Frente comercial', d: 'Cercanía con el mercado norteamericano y sus tiempos.' },
      ],
    },
    pains: {
      eyebrow: 'Lo que ya está pasando',
      title: 'El 96% de las brechas vienen por tres caminos.\nProbablemente uno de ellos te toca hoy.',
      sub: 'Según el Verizon DBIR 2025, en empresas como la tuya — entre 10 y 250 empleados — la intrusión de sistemas, la ingeniería social y los ataques web básicos concentran la mayoría de incidentes. El ransomware aparece en el 88% de los casos.',
      items: [
        {
          k: '01',
          t: 'Fraude por correo (BEC)',
          d: 'Un proveedor cambia su cuenta bancaria por email. Nadie llama a verificar. El pago se va a otra cuenta. Sin SPF, DKIM, DMARC y doble aprobación, esto pasa.',
        },
        {
          k: '02',
          t: 'Microsoft 365 mal configurado',
          d: 'MFA desactivado para algún usuario, forwarding externo abierto, Conditional Access ausente. Una contraseña filtrada y el atacante entra como si fuera tuyo.',
        },
        {
          k: '03',
          t: 'Phishing creíble por IA',
          d: 'Los señuelos ya no tienen faltas. Si tu equipo no entrena con simulaciones cortas y continuas, alguien hará clic. La pregunta es cuándo.',
        },
        {
          k: '04',
          t: 'Ransomware sin plan',
          d: 'Las copias existen pero nadie las ha probado. No hay playbook, ni contactos, ni decisiones tomadas. Cuando llega el incidente, se pierden días — y dinero.',
        },
      ],
    },
    services: {
      eyebrow: 'Q-Secure · Ciberseguridad',
      title: 'Nueve servicios. Alcance, entregable y precio cerrados en cada uno.',
      sub: 'Nuestro pilar más maduro, en tres familias: diagnóstico y estrategia, protección y operación, y vigilancia y respuesta. Cada servicio con entregable definido, alcance claro y precio cerrado antes de empezar.',
      priceNote: 'Propuesta cerrada y precio fijo en 24 h.',
      families: [
        { t: 'Diagnóstico y estrategia', d: 'Sabe dónde estás antes de invertir.' },
        { t: 'Protección y operación', d: 'Protección que escala contigo.' },
        { t: 'Vigilancia y respuesta', d: 'Anticipa la amenaza, responde más rápido.' },
      ],
      items: [
        {
          code: 'Q-Start',
          t: 'Diagnóstico de ciberseguridad',
          d: 'Auditoría de correo, identidad, Microsoft 365 o Google Workspace, web pública, TLS, copias y plan de respuesta. Scorecard ejecutivo + top 15 riesgos + roadmap 90 días.',
          bullets: ['Scorecard ejecutivo', 'Top 15 riesgos priorizados', 'Quick wins 30 días', 'Roadmap 90 días'],
          time: '7 días hábiles',
          price: 'desde 1.250 €',
          slug: 'auditoria-ciberseguridad-pymes',
        },
        {
          code: 'Q-365 Shield',
          t: 'Seguridad Microsoft 365',
          d: 'Hardening de identidad y tenant: MFA forzado, Conditional Access, revisión de forwarding y accesos privilegiados, etiquetado externo, copias y retención.',
          bullets: ['MFA y Conditional Access', 'Auditoría de accesos', 'Forwarding y reglas de buzón', 'Copias y retención'],
          time: '2–3 semanas',
          price: 'desde 1.850 €',
          slug: 'seguridad-microsoft-365-empresa',
        },
        {
          code: 'Q-Mail Shield',
          t: 'Correo seguro y anti-fraude BEC',
          d: 'SPF, DKIM y DMARC bien desplegados, banners de correo externo, doble aprobación para cambios bancarios y playbook anti-fraude del CEO y proveedores.',
          bullets: ['SPF · DKIM · DMARC', 'Procedimiento anti-BEC', 'Doble aprobación de pagos', 'Banners de correo externo'],
          time: '1–2 semanas',
          price: 'desde 950 €',
          slug: 'email-bec-spf-dkim-dmarc',
        },
        {
          code: 'Q-Phishing Test',
          t: 'Simulación de phishing y concienciación',
          d: 'Campañas cortas y continuas (no un PDF anual). Plantillas en español neutro. Microlearning post-clic y reporting ejecutivo mensual.',
          bullets: ['Campañas mensuales', 'Microlearning post-clic', 'Reporting ejecutivo', 'Kit de concienciación'],
          time: 'Continuo · cuota mensual',
          price: 'desde 290 €/mes',
          slug: 'simulacion-phishing-empresa',
        },
        {
          code: 'Q-Incident',
          t: 'Plan de respuesta a incidentes',
          d: 'Playbook a medida con roles, decisiones y contactos, prueba de restauración de copias y un simulacro de mesa (tabletop) con tu equipo directivo.',
          bullets: ['Playbook editable', 'Prueba de copias', 'Tabletop con dirección', 'Contactos y plantillas legales'],
          time: '2 semanas',
          price: 'desde 1.150 €',
          slug: 'plan-respuesta-incidentes-pyme',
        },
        {
          code: 'Q-CISO',
          t: 'vCISO Lite y continuidad',
          d: 'Gobierno práctico mensual: riesgo vivo, seguimiento de acciones, mini comité, drill de incidentes y carpeta de evidencias para NIS2 o auditorías.',
          bullets: ['Revisión mensual', 'Comité ejecutivo', 'Drill de incidentes', 'Evidencias NIS2 / auditoría'],
          time: 'Continuo · cuota mensual',
          price: 'desde 590 €/mes',
          slug: 'vciso-pyme',
        },
        {
          code: 'Q-Dark Alert',
          t: 'Vigilancia de dark web y filtraciones',
          d: 'Monitorizamos dark web, foros y volcados de datos en busca de credenciales, dominios y marca de tu empresa. Si algo aparece, recibes alerta con plan de acción — no un susto sin contexto.',
          bullets: ['Vigilancia continua de credenciales', 'Dominios, correos y marca', 'Alerta con plan de acción', 'Informe mensual ejecutivo'],
          time: 'Continuo · cuota mensual',
          price: 'desde 150 €/mes',
          slug: 'vigilancia-dark-web-empresa',
        },
        {
          code: 'Q-Insure',
          t: 'Preparación para el ciberseguro',
          d: 'Te dejamos a punto para contratar o renovar un ciberseguro: evaluación previa, respuesta al cuestionario de la aseguradora y cierre de los controles mínimos que exigen.',
          bullets: ['Evaluación pre-póliza', 'Respuesta al cuestionario', 'Controles mínimos exigidos', 'También cuestionarios de clientes'],
          time: '1–2 semanas',
          price: 'desde 490 €',
          slug: 'ciberseguro-pyme',
        },
        {
          code: 'Q-AI Ready',
          t: 'Seguridad del uso de IA',
          d: 'Tu equipo ya usa ChatGPT, Copilot o Gemini — con o sin permiso. Política de uso de IA, evaluación de herramientas, configuración segura de Copilot en Microsoft 365 y formación corta al equipo.',
          bullets: ['Política de uso de IA', 'Evaluación de herramientas', 'Copilot M365 seguro', 'Formación al equipo'],
          time: '1–2 semanas',
          price: 'desde 690 €',
          slug: 'seguridad-ia-empresa',
        },
      ],
    },
    method: {
      eyebrow: 'Método',
      title: 'Cuatro pasos. Del diagnóstico a producción.',
      sub: 'El mismo método para seguridad, datos, IA o software — diseñado para que un comité de dirección apruebe cada fase sin necesidad de un equipo técnico interno.',
      steps: [
        { k: '01', t: 'Escucha', d: 'Una llamada de 30 minutos con quien luego ejecuta. Entendemos tu operación, tus sistemas y dónde duele.' },
        { k: '02', t: 'Diagnóstico', d: 'Alcance y precio cerrados. Auditamos seguridad, datos, IA o el sistema en cuestión y priorizamos lo que de verdad mueve la aguja.' },
        { k: '03', t: 'Producción', d: 'Ejecutamos contra una línea base acordada. Llevamos la solución a producción — gobernada, segura y medible. Si no mejora, no avanza.' },
        { k: '04', t: 'Continuidad', d: 'Operación gestionada y transferencia a tu equipo. Documentación, evidencias y salida limpia: el código y los datos son tuyos.' },
      ],
    },
    deliverable: {
      eyebrow: 'Qué recibes',
      title: 'No te entregamos PowerPoints. Te entregamos decisiones.',
      sub: 'Cada cliente recibe la misma estructura: un scorecard ejecutivo de una página, una matriz de riesgos priorizados y un roadmap con tiempos y responsables.',
      label: 'Vista previa · informe Q-Start',
    },
    sectors: {
      eyebrow: 'Sectores',
      title: 'Hablamos el idioma de tu sector.',
      sub: 'Empezamos por los perfiles donde más rápido se entiende y se cierra. Si tu sector no aparece aquí, pregúntanos.',
      items: [
        { t: 'Servicios financieros y fintech', d: 'Riesgo, fraude y decisiones en tiempo real sobre tus sistemas, con cumplimiento y datos bajo control.' },
        { t: 'Salud y healthtech', d: 'Datos especialmente protegidos: IA gobernada, analítica clínica y continuidad, con RGPD de serie.' },
        { t: 'Industria y manufactura', d: 'Moderniza el legacy y lleva los datos de planta a la mesa de decisión — y cierra las puertas de entrada.' },
        { t: 'Retail y e-commerce', d: 'Analítica de demanda, surtido y personalización; y la operación protegida frente al fraude.' },
        { t: 'Servicios profesionales', d: 'Despachos y asesorías: Copilot seguro, automatización y confidencialidad. Cero margen para el error.' },
      ],
    },
    resources: {
      eyebrow: 'Recursos',
      title: 'Llévate algo útil antes de hablar con nosotros.',
      sub: 'Materiales gratuitos, sin paywall técnico. Basados en NIST, CIS, INCIBE y CISA — no en relleno.',
      items: [
        { t: 'Checklist de ciberhigiene', d: '32 controles esenciales para pymes basados en NIST CSF 2.0 y CIS IG1.', tag: 'PDF · 32 controles', href: '/resources/checklist-ciberhigiene-qerub.pdf' },
        { t: 'Guía de phishing y BEC', d: 'Cómo detectar y bloquear fraude por correo. Procedimiento de doble aprobación incluido.', tag: 'PDF · guía práctica', href: '/resources/guia-phishing-bec-qerub.pdf' },
        { t: 'Plantilla de respuesta a incidentes', d: 'Playbook editable con roles, decisiones y contactos. Lista para imprimir.', tag: 'DOCX editable', href: '/resources/plantilla-respuesta-incidentes-qerub.docx' },
      ],
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'Lo que nos preguntan antes de empezar.',
      items: [
        {
          q: '¿Solo hacéis ciberseguridad, o también IA, datos y software?',
          a: 'Las cuatro cosas, con un mismo equipo senior y precio cerrado. La ciberseguridad (Q-Secure) es nuestro pilar más maduro; IA y datos (Q-Intelligence) y software a medida (Q-Build) se entregan con alcance acotado, precio cerrado y total transparencia.',
        },
        {
          q: '¿Cómo funciona el modelo de equipos senior (Q-Pod)?',
          a: 'Te presentamos una terna senior en 5–10 días, con CV, años de experiencia y stack. La persona se integra en tu equipo y trabaja en tu huso horario. Pagas resultado, no sillas, y si en las dos primeras semanas no encaja, la cambiamos sin coste. Sin junior facturados.',
        },
        {
          q: '¿Tenéis oficinas en tres países?',
          a: 'Operamos en tres husos horarios — España (cumplimiento europeo), Argentina (entrega senior nearshore) y Estados Unidos (frente comercial) — para estar cerca de tu negocio a la hora que lo necesitas. No te vendemos una "gran firma" que no somos: te decimos exactamente qué hay en cada sitio.',
        },
        {
          q: '¿Cuánto cuesta el diagnóstico Q-Start?',
          a: 'Precio cerrado en función del tamaño de tu organización. Te enviamos una propuesta concreta en 24 horas tras la primera llamada. Sin sorpresas.',
        },
        {
          q: '¿Necesitamos equipo técnico interno para trabajar con vosotros?',
          a: 'No. Q-Start está diseñado para que la dirección entienda y decida sin un CISO interno. Si tienes proveedor IT, coordinamos con él.',
        },
        {
          q: '¿Y si ya hicimos una auditoría hace tiempo?',
          a: 'Mejor. Partimos de ahí, no de cero. Validamos qué se ejecutó, qué quedó abierto y dónde están hoy los riesgos vivos.',
        },
        {
          q: '¿Trabajáis con NIS2?',
          a: 'Sí. Q-CISO está pensado para generar evidencias trazables de gobierno, gestión de incidentes y continuidad — los pilares de NIS2.',
        },
        {
          q: '¿Hacéis pentesting?',
          a: 'No como puerta de entrada. Lo introducimos cuando la postura base ya está sana. Antes de eso, un pentest solo confirma lo que ya sabemos.',
        },
        {
          q: '¿Puedo contrataros solo para formación?',
          a: 'Sí. Q-Phishing Test se contrata de forma independiente como cuota mensual.',
        },
      ],
    },
    finalCta: {
      title: 'Empieza por una conversación.\nTécnica, sin deck, con quien ejecuta.',
      sub: 'Treinta minutos. Cero compromiso. Salimos con un alcance claro y un precio cerrado — y si todavía no te toca invertir, te lo decimos.',
      primary: 'Solicitar diagnóstico',
      secondary: 'Hablar primero por correo',
    },
    contact: {
      eyebrow: 'Contacto',
      title: 'Cuéntanos qué está pasando.',
      sub: 'Respondemos en menos de 24 horas hábiles. La primera llamada es gratis y sin compromiso.',
      fields: {
        name: 'Nombre',
        company: 'Empresa',
        email: 'Correo corporativo',
        phone: 'Teléfono (opcional)',
        size: 'Tamaño de tu empresa',
        sizeOpts: ['1–9 empleados', '10–49 empleados', '50–99 empleados', '100–249 empleados', '250–500 empleados', 'Más de 500'],
        msg: 'Cuéntanos brevemente qué te preocupa',
        msgPh: 'Ej: Recibimos intentos de fraude por correo y queremos revisar Microsoft 365…',
        consent: 'Acepto la política de privacidad',
        submit: 'Solicitar diagnóstico',
        trustNote: 'Respuesta en menos de 24 h hábiles · Sin compromiso · Tus datos nunca se comparten con terceros',
      },
      altTitle: 'O escríbenos directamente',
      altMail: window.QERUB_CONTACT.email,
      altPhone: window.QERUB_CONTACT.phone,
      altWhatsapp: 'WhatsApp Business',
      altHours: window.QERUB_CONTACT.hoursEs,
    },
    about: {
      eyebrow: 'Sobre Qerub',
      title: 'Hacemos tecnología útil.\nNo vendemos humo.',
      body: [
        'Qerub nace de una observación simple: la mayoría de las empresas medianas no necesita una gran consultora que facture horas. Necesita criterio senior, decisiones claras y alguien que se haga cargo — en ciberseguridad, en datos, en IA y en el software que de verdad mueve su negocio.',
        'Trabajamos con manuales públicos — NIST, CIS, ENISA, INCIBE y los marcos de IA y datos — porque la buena tecnología se construye con decisiones repetidas y medibles, no con humo.',
        'Operamos en tres husos horarios — España, Argentina y Estados Unidos — con equipos senior, sin contratos eternos y sin facturas opacas. Cada propuesta tiene alcance, precio y entregable. Si no podemos ayudarte, lo decimos antes de cobrar.',
      ],
      values: [
        { t: 'Claridad antes que tecnicismo', d: 'Si un comité de dirección no lo entiende, no sirve.' },
        { t: 'Prioridad antes que cobertura', d: 'Cubrimos lo que más reduce riesgo, no lo que mejor suena.' },
        { t: 'Evidencia antes que opinión', d: 'Cada recomendación se apoya en marco público y dato.' },
      ],
    },
    footer: {
      tag: 'WE SECURE · YOU LIVE SAFE',
      cols: {
        services: 'Servicios',
        company: 'Empresa',
        resources: 'Recursos',
      },
      links: {
        services: ['Q-Secure · Ciberseguridad', 'Q-Intelligence · IA y datos', 'Q-Build · Software a medida', 'Q-Pod · Equipos senior'],
        company: ['Sobre Qerub', 'Sectores', 'Contacto'],
        resources: ['Checklist de ciberhigiene', 'Guía phishing/BEC', 'Plantilla de respuesta a incidentes'],
      },
      legal: '© 2026 Qerub · Aviso legal · Política de privacidad · Cookies',
      base: 'Consultoría IT para empresas en crecimiento. España · Argentina · EE.UU.',
      privacy: 'Configuración de privacidad',
    },
    cookies: {
      title: 'Configuración de privacidad',
      body: 'Para que usted tenga la mejor experiencia posible, usamos cookies y otras tecnologías similares. Algunas cookies son necesarias para que el sitio web funcione, y no se pueden rechazar. Puede aceptar o rechazar las cookies adicionales, que se usan solamente para mejorar la experiencia del usuario. Estos datos nunca se pondrán a la venta ni se utilizarán con fines comerciales.',
      bodyMore: 'Si desea saber más, lea nuestra Política global sobre el uso de cookies y otras tecnologías. También puede personalizar en cualquier momento su configuración en la Configuración de privacidad.',
      policyLink: 'Política global sobre el uso de cookies',
      accept: 'Aceptar',
      reject: 'Rechazar',
      customize: 'Personalizar',
      save: 'Guardar selección',
      categories: [
        { k: 'necessary', t: 'Cookies necesarias', d: 'Imprescindibles para que el sitio web funcione (sesión, seguridad, idioma). No se pueden desactivar.', locked: true },
        { k: 'analytics', t: 'Cookies analíticas', d: 'Nos ayudan a entender cómo usas el sitio, de forma agregada y anónima, para mejorar el contenido.' },
        { k: 'marketing', t: 'Cookies de marketing', d: 'Permiten medir la efectividad de campañas y mostrar contenido relevante. Nunca se venden a terceros.' },
        { k: 'preferences', t: 'Cookies de preferencias', d: 'Recuerdan tus elecciones (idioma, región) para que no tengas que repetirlas en cada visita.' },
      ],
      reopen: 'Configuración de privacidad',
    },
  },

  'en-US': {
    locale: 'en-US',
    nav: {
      services: 'Services',
      method: 'Method',
      sectors: 'Sectors',
      resources: 'Resources',
      about: 'About',
      contact: 'Contact',
      cta: 'Request assessment',
    },
    hero: {
      eyebrow: 'IT consulting for growing companies',
      title: 'Your senior IT team,\nwith fixed scope and fixed price.',
      sub: 'AI, data, custom software, and cybersecurity. What a big firm would bill you by the hour, we deliver as an outcome. No junior staff on the invoice.',
      primary: 'Request assessment',
      secondary: 'See what we do',
      tag: 'Q-Start · Closed assessment in 7 business days',
      presence: 'Three time zones · Spain · Argentina · U.S.',
      slides: [
        {
          title: 'Your senior IT team,\nwith fixed scope and fixed price.',
          sub: 'AI, data, custom software, and cybersecurity. What a big firm would bill you by the hour, we deliver as an outcome. No junior staff on the invoice.',
        },
        {
          title: 'From pilot to production.\nNo handoffs, no slideware.',
          sub: 'We take your AI agents, data platform, and custom software all the way to production — governed and secure. One partner for AI, data, software, and security.',
        },
        {
          title: 'Senior talent embedded\nin your team in days, not months.',
          sub: 'Senior AI, data, cloud, and security teams that work in your time zone and operate as your own. Pay for outcomes, not seats.',
        },
      ],
    },
    trust: {
      title: 'We work with the frameworks that matter',
      items: ['NIST CSF 2.0', 'CIS Controls IG1', 'ENISA SME', 'INCIBE', 'CISA', 'NIS2'],
    },
    pillars: {
      eyebrow: 'What we do',
      title: 'One senior partner for all four fronts.',
      sub: 'Qerub is an IT consultancy for SMBs and mid-market companies (50-300 employees): four fronts delivered by one senior team at a fixed price — AI and data, custom software, embedded senior teams and cybersecurity. No junior staff billed, operating across three time zones: Spain, Argentina and the United States.',
      items: [
        {
          code: 'Q-Secure', t: 'Cybersecurity', tagline: 'Security as a business advantage, not a brake.',
          intro: 'Q-Secure is Qerub’s most mature pillar: nine cybersecurity services with fixed scope and price, aligned with NIST CSF 2.0, CIS Controls IG1 and NIS2.',
          forWhom: 'CEO · CISO · IT', status: 'Live', to: 'services',
          subs: [
            { n: 'Q-Start · Cybersecurity assessment', d: 'We audit email, identity, Microsoft 365 or Google Workspace, public web, TLS, backups and response plan. Executive scorecard, top 15 risks and a 90-day roadmap in 7 business days.', href: '/en-us/servicios/auditoria-ciberseguridad-pymes' },
            { n: 'Q-365 Shield · Microsoft 365 security', d: 'Identity and tenant hardening: enforced MFA, Conditional Access, forwarding and privileged-access review, external tagging, backups and retention.', href: '/en-us/servicios/seguridad-microsoft-365-empresa' },
            { n: 'Q-Mail Shield · Secure email & BEC anti-fraud', d: 'SPF, DKIM and DMARC deployed properly, external-email banners, dual approval for bank-detail changes and a CEO/supplier anti-fraud playbook.', href: '/en-us/servicios/email-bec-spf-dkim-dmarc' },
            { n: 'Q-Phishing Test · Phishing simulation & awareness', d: 'Short, continuous campaigns with post-click microlearning and monthly executive reporting. Not an annual PDF.', href: '/en-us/servicios/simulacion-phishing-empresa' },
            { n: 'Q-Incident · Incident response plan', d: 'A tailored playbook with roles, decisions and contacts, a backup-restore test and a tabletop drill with your leadership.', href: '/en-us/servicios/plan-respuesta-incidentes-pyme' },
            { n: 'Q-CISO · vCISO & continuity', d: 'Practical monthly governance: live risk, action tracking, a mini committee, an incident drill and an evidence folder for NIS2 or audits.', href: '/en-us/servicios/vciso-pyme' },
            { n: 'Q-Dark Alert · Dark web & breach monitoring', d: 'We monitor the dark web, forums and data dumps for your credentials, domains and brand. If something surfaces, you get an alert with an action plan.', href: '/en-us/servicios/vigilancia-dark-web-empresa' },
            { n: 'Q-Insure · Cyber-insurance readiness', d: 'We get you ready to buy or renew cyber insurance: pre-assessment, answering the insurer’s questionnaire and closing the minimum required controls.', href: '/en-us/servicios/ciberseguro-pyme' },
            { n: 'Q-AI Ready · AI usage security', d: 'AI usage policy, tool assessment, secure Copilot configuration in Microsoft 365 and short team training. Your team already uses ChatGPT, Copilot or Gemini.', href: '/en-us/servicios/seguridad-ia-empresa' },
          ],
        },
        {
          code: 'Q-Intelligence', t: 'AI & Data', tagline: 'You have the data. You’re missing the decisions — and AI that reaches production.',
          intro: 'Q-Intelligence is Qerub’s AI and data front: it takes AI from use case to production with measurable ROI, organizes your data for self-service BI and governs AI use under the EU AI Act.',
          forWhom: 'CEO · CIO', status: 'Available', to: 'contact', href: '/en-us/servicios/consultoria-ia-datos-empresa',
          subs: [
            { n: 'AI-readiness assessment', d: 'In 7 days we map where your data lives, which decision is worth automating and a realistic estimate. You leave with a prioritized case.' },
            { n: 'Applied generative AI', d: 'Agents, assistants and RAG over your own documentation, with secure retrieval and traceability for every answer.' },
            { n: 'M365 Copilot adoption', d: 'Microsoft Copilot rollout per department with real use cases and training; value is in usage, not the license. Coordinated with Q-365 Shield.' },
            { n: 'Data platform & BI', d: 'Clean data and a self-service BI (Power BI) your committee opens and understands. “AI-ready data”: data quality and governance.' },
            { n: 'AI governance (EU AI Act)', d: 'Inventory of uses, policy and risk controls, plus surfacing your team’s “shadow AI”. Documented compliance, not a slide deck.' },
            { n: 'Production rollout', d: 'Deploy, monitor, alert on drift and hand over to your team. No endless dependency.' },
          ],
        },
        {
          code: 'Q-Build', t: 'Custom software', tagline: 'The software your business needs and off-the-shelf won’t give you.',
          intro: 'Q-Build is Qerub’s custom software front: applications, integrations and modernization with senior judgment and security by design. The code and data belong to the client.',
          forWhom: 'CEO · CTO', status: 'Available', to: 'contact', href: '/en-us/servicios/desarrollo-software-medida-empresa',
          subs: [
            { n: 'Custom development', d: 'Applications and internal tools that fit your real operation, not the other way around. Web, dashboards and automations.' },
            { n: 'Integrations', d: 'We connect CRM, ERP, billing, payments and APIs so your systems stop speaking different languages.' },
            { n: 'Application modernization', d: 'We take your legacy out of the bottleneck, piece by piece without stopping the business — the prerequisite for using AI and data.' },
            { n: 'MVP with senior judgment', d: 'From idea to a usable product with the right calls where it matters: identity, payments and regulated data. Anti “vibe coding”.' },
            { n: 'Cloud-native', d: 'Deployed to your cloud (Azure/AWS) with cost and operations best practices. No surprises on the bill.' },
            { n: 'Security by design', d: 'Our root is cybersecurity; every build starts with identity, secrets and data handled properly.' },
          ],
        },
        {
          code: 'Q-Pod', t: 'Embedded senior teams', tagline: 'Senior talent that embeds in your team in days. Pay for outcomes, not seats.',
          intro: 'Q-Pod is Qerub’s staff augmentation and managed-operations front: senior profiles embedded in your team in days, in your time zone. You pay for results, not seats.',
          forWhom: 'Head of Talent · CIO', status: 'Available', to: 'contact', href: '/en-us/servicios/staff-augmentation-nearshore',
          subs: [
            { n: 'Senior profiles', d: 'Data engineers, backend developers, cloud and cybersecurity specialists. We share CV, years and stack before anyone joins.' },
            { n: 'Embedded in your team', d: 'They work under your backlog and your tools, as one of yours — not an external black box that delivers and disappears.' },
            { n: 'Nearshore across three zones', d: 'Spain, Argentina (UTC-3) and the US, with real overlap to iterate same-day. Strong English, proximity and quality.' },
            { n: 'vCISO & fractional vCIO/vCTO', d: 'Managed operation: a veteran a few hours a week instead of a full-time C-level you can’t afford.' },
            { n: 'Replacement SLA', d: 'If the profile doesn’t fit in the first two weeks, we replace it at no cost. 100% senior, no junior staff billed.' },
            { n: 'Clean exit', d: 'The knowledge, code and data are yours. We document and hand over. No endless dependency.' },
          ],
        },
      ],
      note: 'Q-Secure is our most mature pillar. Q-Intelligence and Q-Build are delivered with tight scope, fixed price and full transparency.',
    },
    decisors: {
      eyebrow: 'Who we work for',
      title: 'We speak the language of whoever decides.',
      sub: 'Three different conversations, one principle: clarity, seniority and fixed price.',
      items: [
        { role: 'For the CEO', t: 'Technology your leadership gets on the first read.', d: 'AI, data, software and cybersecurity with fixed scope and price. No surprises, no junior staff billed.', cta: 'A conversation, no sales deck' },
        { role: 'For the CIO / CTO', t: 'From pilot to production, no slideware.', d: 'One partner for AI, data, software and security — governed, secure and embedded in your stack. The code and the data are yours.', cta: 'Book a technical review of your stack' },
        { role: 'For the Head of Talent', t: 'Senior talent in your team in days, not months.', d: 'Senior teams that work in your time zone and operate as your own. Shortlist in 5–10 days. No junior staff billed.', cta: 'Tell us the role you’re missing' },
      ],
    },
    proof: {
      eyebrow: 'How we work',
      title: 'No brochure. Proof of method, not promises.',
      sub: 'We’re a young firm and we say it plainly: our credibility is in the method, the transparency and the senior talent — not in inflated client numbers.',
      metrics: [
        { v: '7', u: 'days', label: 'from assessment to action plan' },
        { v: '5–10', u: 'days', label: 'to send you a senior shortlist' },
        { v: '100', u: '%', label: 'senior profiles · no junior staff billed' },
        { v: '0', u: '€', label: 'surprises: fixed scope and price before we start' },
      ],
      cta: {
        tag: 'Start here',
        t: 'Start with a low-risk assessment.',
        d: 'We set fixed scope and price before we begin and validate the use case with clear ROI before scaling. No long commitments, full transparency.',
        cta: 'Talk to a senior partner',
      },
    },
    geo: {
      eyebrow: 'Where we are',
      title: 'We operate across three time zones.',
      sub: 'European regulatory rigor, senior talent in Latin America and commercial proximity in the United States. Close to your business, when you need it.',
      items: [
        { city: 'Spain', role: 'European compliance', d: 'GDPR, NIS2 and the EU AI Act. Commercial face for Europe.' },
        { city: 'Argentina', role: 'Senior nearshore delivery', d: 'Senior talent in UTC-3, overlapping with all of the Americas and strong English.' },
        { city: 'United States', role: 'Commercial front', d: 'Proximity to the North American market and its pace.' },
      ],
    },
    pains: {
      eyebrow: 'What\u2019s already happening',
      title: '96% of breaches come through three paths.\nOne of them is probably hitting you today.',
      sub: 'According to Verizon DBIR 2025, in companies like yours — between 10 and 250 employees — system intrusion, social engineering and basic web attacks concentrate most incidents. Ransomware shows up in 88% of cases.',
      items: [
        { k: '01', t: 'Email fraud (BEC)', d: 'A supplier changes their bank account via email. No one calls to verify. The payment lands somewhere else. Without SPF, DKIM, DMARC and dual approval, this happens.' },
        { k: '02', t: 'Misconfigured Microsoft 365', d: 'MFA off for one user, external forwarding open, no Conditional Access. One leaked password and the attacker walks in as if they were you.' },
        { k: '03', t: 'AI-grade phishing', d: 'Lures have no typos anymore. If your team doesn\u2019t train with short, continuous simulations, someone will click. The question is when.' },
        { k: '04', t: 'Ransomware without a plan', d: 'Backups exist but nobody has tested them. No playbook, no contacts, no decisions made. When the incident hits, you lose days — and money.' },
      ],
    },
    services: {
      eyebrow: 'Q-Secure · Cybersecurity',
      title: 'Nine services. Closed scope, deliverable and price on each.',
      sub: 'Our most mature pillar, in three families: assessment & strategy, protection & operations, and monitoring & response. Each service has a defined deliverable, clear scope and a closed price before we start.',
      priceNote: 'Closed proposal and fixed price within 24 h.',
      families: [
        { t: 'Assessment & strategy', d: 'Know where you stand before you invest.' },
        { t: 'Protection & operations', d: 'Protection that scales with you.' },
        { t: 'Monitoring & response', d: 'Anticipate the threat, respond faster.' },
      ],
      items: [
        { code: 'Q-Start', t: 'Cybersecurity assessment', d: 'Audit of email, identity, Microsoft 365 or Google Workspace, public web, TLS, backups and incident plan. Executive scorecard + top 15 risks + 90-day roadmap.', bullets: ['Executive scorecard', 'Top 15 prioritised risks', '30-day quick wins', '90-day roadmap'], time: '7 business days', price: 'from \u20ac1,250', slug: 'auditoria-ciberseguridad-pymes' },
        { code: 'Q-365 Shield', t: 'Microsoft 365 security', d: 'Identity and tenant hardening: enforced MFA, Conditional Access, forwarding and privileged access review, external tagging, backups and retention.', bullets: ['MFA & Conditional Access', 'Access audit', 'Forwarding & mailbox rules', 'Backups & retention'], time: '2\u20133 weeks', price: 'from \u20ac1,850', slug: 'seguridad-microsoft-365-empresa' },
        { code: 'Q-Mail Shield', t: 'Email security & BEC anti-fraud', d: 'SPF, DKIM and DMARC properly deployed, external email banners, dual approval for bank-detail changes and a CEO/vendor fraud playbook.', bullets: ['SPF \u00b7 DKIM \u00b7 DMARC', 'Anti-BEC procedure', 'Dual payment approval', 'External email banners'], time: '1\u20132 weeks', price: 'from \u20ac950', slug: 'email-bec-spf-dkim-dmarc' },
        { code: 'Q-Phishing Test', t: 'Phishing simulation & awareness', d: 'Short, continuous campaigns (not a yearly PDF). Templates in neutral Spanish and English. Post-click microlearning and monthly executive reporting.', bullets: ['Monthly campaigns', 'Post-click microlearning', 'Executive reporting', 'Awareness kit'], time: 'Ongoing \u00b7 monthly fee', price: 'from \u20ac290/mo', slug: 'simulacion-phishing-empresa' },
        { code: 'Q-Incident', t: 'Incident response plan', d: 'Tailored playbook with roles, decisions and contacts, backup restoration test and a tabletop exercise with your management team.', bullets: ['Editable playbook', 'Backup restore test', 'Management tabletop', 'Contacts & legal templates'], time: '2 weeks', price: 'from \u20ac1,150', slug: 'plan-respuesta-incidentes-pyme' },
        { code: 'Q-CISO', t: 'vCISO Lite & continuity', d: 'Practical monthly governance: live risk register, action tracking, exec mini-committee, incident drill and evidence folder for NIS2 or audits.', bullets: ['Monthly review', 'Exec committee', 'Incident drill', 'NIS2 / audit evidence'], time: 'Ongoing \u00b7 monthly fee', price: 'from \u20ac590/mo', slug: 'vciso-pyme' },
        { code: 'Q-Dark Alert', t: 'Dark web & breach monitoring', d: 'We monitor the dark web, forums and data dumps for your company credentials, domains and brand. If something surfaces, you get an alert with an action plan — not a scare without context.', bullets: ['Continuous credential monitoring', 'Domains, emails & brand', 'Alert with action plan', 'Monthly executive report'], time: 'Ongoing \u00b7 monthly fee', price: 'from \u20ac150/mo', slug: 'vigilancia-dark-web-empresa' },
        { code: 'Q-Insure', t: 'Cyber insurance readiness', d: 'We get you ready to buy or renew cyber insurance: pre-policy assessment, insurer questionnaire answered and the minimum required controls closed.', bullets: ['Pre-policy assessment', 'Questionnaire response', 'Minimum required controls', 'Client questionnaires too'], time: '1\u20132 weeks', price: 'from \u20ac490', slug: 'ciberseguro-pyme' },
        { code: 'Q-AI Ready', t: 'AI usage security', d: 'Your team already uses ChatGPT, Copilot or Gemini — with or without permission. AI-use policy, tool assessment, secure Microsoft 365 Copilot configuration and a short team training.', bullets: ['AI use policy', 'Tool assessment', 'Secure M365 Copilot', 'Team training'], time: '1\u20132 weeks', price: 'from \u20ac690', slug: 'seguridad-ia-empresa' },
      ],
    },
    method: {
      eyebrow: 'Method',
      title: 'Four steps. From assessment to production.',
      sub: 'The same method for security, data, AI or software — designed so an exec committee can approve each phase without needing an internal technical team.',
      steps: [
        { k: '01', t: 'Listen', d: 'A 30-minute call with the people who do the work. We understand your operation, your systems and where it hurts.' },
        { k: '02', t: 'Assess', d: 'Fixed scope and price. We audit security, data, AI or the system in question and prioritise what actually moves the needle.' },
        { k: '03', t: 'Production', d: 'We execute against an agreed baseline. We take the solution to production — governed, secure and measurable. If it doesn’t improve, it doesn’t ship.' },
        { k: '04', t: 'Continuity', d: 'Managed operation and handover to your team. Documentation, evidence and a clean exit: the code and the data are yours.' },
      ],
    },
    deliverable: {
      eyebrow: 'What you get',
      title: 'We don\u2019t hand over PowerPoints. We hand over decisions.',
      sub: 'Every client gets the same structure: a one-page executive scorecard, a prioritised risk matrix and a roadmap with timing and owners.',
      label: 'Preview · Q-Start report',
    },
    sectors: {
      eyebrow: 'Sectors',
      title: 'We speak your industry\u2019s language.',
      sub: 'We start with profiles where the conversation closes fastest. If your sector isn\u2019t here, ask us.',
      items: [
        { t: 'Financial services & fintech', d: 'Risk, fraud and real-time decisions on your systems, with compliance and data under control.' },
        { t: 'Health & healthtech', d: 'Specially protected data: governed AI, clinical analytics and continuity, with GDPR built in.' },
        { t: 'Industry & manufacturing', d: 'Modernize the legacy and bring plant data to the decision table \u2014 and close the entry doors.' },
        { t: 'Retail & e-commerce', d: 'Demand, assortment and personalization analytics; and an operation protected from fraud.' },
        { t: 'Professional services', d: 'Firms and advisories: secure Copilot, automation and confidentiality. Zero room for error.' },
      ],
    },
    resources: {
      eyebrow: 'Resources',
      title: 'Take something useful before we even talk.',
      sub: 'Free materials, no technical paywall. Based on NIST, CIS, INCIBE and CISA — not filler.',
      items: [
        { t: 'Cyber hygiene checklist', d: '32 essential controls for SMBs based on NIST CSF 2.0 and CIS IG1.', tag: 'PDF · 32 controls', href: '/resources/checklist-ciberhigiene-qerub.pdf' },
        { t: 'Phishing & BEC guide', d: 'How to detect and block email fraud. Dual-approval procedure included.', tag: 'PDF · practical guide', href: '/resources/guia-phishing-bec-qerub.pdf' },
        { t: 'Incident response template', d: 'Editable playbook with roles, decisions and contacts. Print-ready.', tag: 'Editable DOCX', href: '/resources/plantilla-respuesta-incidentes-qerub.docx' },
      ],
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'What people ask us before starting.',
      items: [
        { q: 'Do you only do cybersecurity, or also AI, data and software?', a: 'All four, with the same senior team and a fixed price. Cybersecurity (Q-Secure) is our most mature pillar; AI and data (Q-Intelligence) and custom software (Q-Build) are delivered with tight scope, fixed price and full transparency.' },
        { q: 'How does the senior-team model (Q-Pod) work?', a: 'We send a senior shortlist in 5–10 days, with CV, years of experience and stack. The person embeds in your team and works in your time zone. You pay for outcomes, not seats, and if it does not fit in the first two weeks, we replace them at no cost. No junior staff billed.' },
        { q: 'Do you have offices in three countries?', a: 'We operate across three time zones — Spain (European compliance), Argentina (senior nearshore delivery) and the United States (commercial front) — to be close to your business when you need it. We will not sell you a "big firm" we are not: we tell you exactly what is in each place.' },
        { q: 'How much is the Q-Start assessment?', a: 'Closed price based on your org size. We send a concrete proposal within 24 hours after the first call. No surprises.' },
        { q: 'Do we need an internal tech team to work with you?', a: 'No. Q-Start is designed for management to understand and decide without an internal CISO. If you have an IT vendor, we coordinate with them.' },
        { q: 'What if we already did an audit a while ago?', a: 'Even better. We start from there, not from zero. We validate what was executed, what remained open and where the live risks are today.' },
        { q: 'Do you work with NIS2?', a: 'Yes. Q-CISO is built to produce traceable governance evidence, incident management and continuity — the pillars of NIS2.' },
        { q: 'Do you do pentesting?', a: 'Not as an entry point. We introduce it once the base posture is healthy. Before that, a pentest only confirms what we already know.' },
        { q: 'Can I hire you only for training?', a: 'Yes. Q-Phishing Test is contracted independently as a monthly fee.' },
      ],
    },
    finalCta: {
      title: 'Start with a conversation.\nTechnical, no deck, with the people who do the work.',
      sub: 'Thirty minutes. Zero commitment. You walk out with clear scope and a closed price — and if it’s not the right time to invest yet, we’ll tell you.',
      primary: 'Request assessment',
      secondary: 'Email us first',
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Tell us what\u2019s going on.',
      sub: 'We reply in under 24 business hours. The first call is free and with no commitment.',
      fields: {
        name: 'Name',
        company: 'Company',
        email: 'Work email',
        phone: 'Phone (optional)',
        size: 'Company size',
        sizeOpts: ['1\u20139 employees', '10\u201349 employees', '50\u201399 employees', '100\u2013249 employees', '250\u2013500 employees', 'More than 500'],
        msg: 'Briefly, what worries you',
        msgPh: 'e.g. We\u2019re seeing email fraud attempts and want to review Microsoft 365\u2026',
        consent: 'I accept the privacy policy',
        submit: 'Request assessment',
        trustNote: 'Reply within 24 business hours \u00b7 No commitment \u00b7 Your data is never shared with third parties',
      },
      altTitle: 'Or write us directly',
      altMail: window.QERUB_CONTACT.email,
      altPhone: window.QERUB_CONTACT.phone,
      altWhatsapp: 'WhatsApp Business',
      altHours: window.QERUB_CONTACT.hoursEn,
    },
    about: {
      eyebrow: 'About Qerub',
      title: 'We build useful technology.\nWe don’t sell smoke.',
      body: [
        'Qerub starts from a simple observation: most mid-sized companies don’t need a big firm billing by the hour. They need senior judgment, clear decisions and someone who takes ownership — in cybersecurity, in data, in AI and in the software that actually moves their business.',
        'We work with public playbooks — NIST, CIS, ENISA, INCIBE and the AI and data frameworks — because good technology is built with decisions repeated and measured, not with smoke.',
        'We operate across three time zones — Spain, Argentina and the United States — with senior teams, no forever contracts and no opaque invoices. Every proposal has scope, price and deliverable. If we can’t help you, we say so before billing.',
      ],
      values: [
        { t: 'Clarity over jargon', d: 'If the exec committee doesn\u2019t get it, it doesn\u2019t work.' },
        { t: 'Priority over coverage', d: 'We cover what reduces most risk, not what sounds best.' },
        { t: 'Evidence over opinion', d: 'Every recommendation is anchored in public framework and data.' },
      ],
    },
    footer: {
      tag: 'WE SECURE · YOU LIVE SAFE',
      cols: {
        services: 'Services',
        company: 'Company',
        resources: 'Resources',
      },
      links: {
        services: ['Q-Secure · Cybersecurity', 'Q-Intelligence · AI & data', 'Q-Build · Custom software', 'Q-Pod · Senior teams'],
        company: ['About Qerub', 'Sectors', 'Contact'],
        resources: ['Cyber hygiene checklist', 'Phishing/BEC guide', 'Incident response template'],
      },
      legal: '© 2026 Qerub · Legal notice · Privacy policy · Cookies',
      base: 'IT consulting for growing companies. Spain · Argentina · U.S.',
      privacy: 'Privacy settings',
    },
    cookies: {
      title: 'Privacy settings',
      body: 'To give you the best possible experience we use cookies and similar technologies. Some cookies are required for the site to work and cannot be rejected. You can accept or reject additional cookies, which are only used to improve your experience. This data is never sold or used for commercial purposes.',
      bodyMore: 'For more details, read our Global cookie policy. You can also personalise your choices at any time in Privacy settings.',
      policyLink: 'Global cookie policy',
      accept: 'Accept',
      reject: 'Reject',
      customize: 'Customise',
      save: 'Save selection',
      categories: [
        { k: 'necessary', t: 'Necessary cookies', d: 'Required for the site to function (session, security, language). Cannot be disabled.', locked: true },
        { k: 'analytics', t: 'Analytics cookies', d: 'Help us understand how you use the site, aggregated and anonymous, so we can improve content.' },
        { k: 'marketing', t: 'Marketing cookies', d: 'Measure campaign effectiveness and show relevant content. Never sold to third parties.' },
        { k: 'preferences', t: 'Preference cookies', d: 'Remember your choices (language, region) so you don\u2019t repeat them every visit.' },
      ],
      reopen: 'Privacy settings',
    },
  },
};
